### Numpy Array Operations

In [13]:
import numpy as np

#### Function 1 - np.concatenate

In [3]:
#Write a short introduction about Numpy and list the chosen functions.

function1 = np.concatenate
function2 = np.transpose
function3 = np.vstack
function4 = np.hsplit
function5 = np.linalg

In [4]:
# Example 1 - working (change this)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

In [5]:
# Example 2 - working
arr1 = [[1, 2, 9], 
        [3, 4., 0]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  9.,  5.,  6.,  7.],
       [ 3.,  4.,  0.,  8.,  9., 10.]])

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

# due to mismatched dimention arr2 would not able to stack underneath arr2, as per axis = 0

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

#### Function 2 - np.transpose

In [14]:
# Example 1 - working
 
arr1 = [[1, 2], 
        [3, 4.]]


i = np.transpose(arr1)
print(i)

[[1. 3.]
 [2. 4.]]


In [15]:
# Example 2 - working
arr2 = [[10, 2], 
        [30, 4.]]


i = np.transpose(arr2)
print(i)

[[10. 30.]
 [ 2.  4.]]


In [17]:
# Example 3 - breaking (to illustrate when it breaks)
arr2 = [[10, 2], 
        [30, 4.]]


i = np.transpose(arr3)
print(i)

# Name error, as arr3 is not mention earlier. Due to this reason, function is not able to find the given array

NameError: name 'arr3' is not defined

#### Function 3 - np.vstack

In [18]:
# Example 1 - working
a = [[1, 2], 
    [3, 4.]]

b = [[10, 2], 
    [3, 40.]]

i = np.vstack((a, b))
print(i)

[[ 1.  2.]
 [ 3.  4.]
 [10.  2.]
 [ 3. 40.]]


In [19]:
# Example 2 - working

i = np.hstack((a, b))
print(i)

[[ 1.  2. 10.  2.]
 [ 3.  4.  3. 40.]]


In [21]:
# Example 3 - breaking (to illustrate when it breaks)
i = np.hstack((A, b))
print(i)

# Name error, as "A" is incorrectly written insted of mentioning "a". Due to this reason, 
# function is not able to the given array. 

NameError: name 'A' is not defined

#### Function 3 - splitting

In [22]:
# Example 1 - working
a = np.array([[1, 3, 5, 7, 9, 11], 
              [2, 4, 6, 8, 10, 12]]) 
  
# horizontal splitting 
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a, 2)) 

Splitting along horizontal axis into 2 parts:
 [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]


In [23]:
# Example 2 - working
# vertical splitting 
print("\nSplitting along vertical axis into 2 parts:\n", np.vsplit(a, 2))


Splitting along vertical axis into 2 parts:
 [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


In [35]:
# Example 3 - breaking (to illustrate when it breaks)
mat = np.array([[68,45,32],
               [53,66,47]])

np.split(mat,2,axis=1)
# The above error tells us that the array should be splitted in equal parts. 
#Changing the splitting parameter to 3 will fix it.

ValueError: array split does not result in an equal division

#### Function 4 - np.datetime64

In [24]:
# Example 1 - working
# creating a date 

today = np.datetime64('2017-02-12') 
print("Date is:", today) 
print("Year is:", np.datetime64(today, 'Y')) 

Date is: 2017-02-12
Year is: 2017


In [25]:
# Example 2 - working
# creating array of dates in a month 

dates = np.arange('2017-02', '2017-03', dtype='datetime64[D]') 
print("\nDates of February, 2017:\n", dates) 
print("Today is February:", today in dates) 


Dates of February, 2017:
 ['2017-02-01' '2017-02-02' '2017-02-03' '2017-02-04' '2017-02-05'
 '2017-02-06' '2017-02-07' '2017-02-08' '2017-02-09' '2017-02-10'
 '2017-02-11' '2017-02-12' '2017-02-13' '2017-02-14' '2017-02-15'
 '2017-02-16' '2017-02-17' '2017-02-18' '2017-02-19' '2017-02-20'
 '2017-02-21' '2017-02-22' '2017-02-23' '2017-02-24' '2017-02-25'
 '2017-02-26' '2017-02-27' '2017-02-28']
Today is February: True


In [36]:
# Example 3 - breaking (to illustrate when it breaks)
# arithmetic operation on dates 

dur = np.datetim64('2014-05-22') - np.datetime64('2016-05-22') 
print("\nNo. of days:", dur) 
print("No. of weeks:", np.timedelta64(dur, 'W')) 

# Numpy library do not have dateim64 function in it. Try using " np.datetime64 "

AttributeError: module 'numpy' has no attribute 'datetim64'

#### Function 5 - np.linalg.matrix_rank

In [37]:
# Example 1 - working
  
A = np.array([[6, 1, 1], 
              [4, -2, 5], 
              [2, 8, 7]]) 
  
print("Rank of A:", np.linalg.matrix_rank(A)) 
print("\nInverse of A:\n", np.linalg.inv(A)) 

Rank of A: 3

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [38]:
# Example 2 - working

print("\nMatrix A raised to power 3:\n", np.linalg.matrix_power(A, 3))


Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


In [42]:
# Example 3 - breaking (to illustrate when it breaks)

print("\nMatrix A raised to power 3:\n", np.linalg.matrix_power(a, -3))

# a = np.array([[1, 3, 5, 7, 9, 11], 
#               [2, 4, 6, 8, 10, 12]])

# a consist different data, then A. Provide variable A data into hyperparamerter

LinAlgError: Last 2 dimensions of the array must be square